---
name: WWW-PriceMinister
version: 0.01
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
abstract: A Perl interface to the PriceMinister web site
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::TreeBuilder: 3
  WWW::Mechanize: 1.20
build_requires:
  Test::More: 0
provides:
  WWW::PriceMinister:
    file: lib/WWW/PriceMinister.pm
    version: 0.01
  WWW::PriceMinister::Item:
    file: lib/WWW/PriceMinister/Item.pm
  WWW::PriceMinister::Object:
    file: lib/WWW/PriceMinister/Object.pm
  WWW::PriceMinister::Offer:
    file: lib/WWW/PriceMinister/Offer.pm
  WWW::PriceMinister::Seller:
    file: lib/WWW/PriceMinister/Seller.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
